### PR TITLE
adjust Base-Reorder link; update action versions; add more apps

### PR DESCRIPTION
**Pull request by Lenni009**

### CODE REVIEW

**Comment by Lenni009** [comment]
@Khaoz-Topsy please take a quick look when you have time so this can  be merged

**Comment by Khaoz-Topsy** [comment]
LGTM 😋

**Comment by Lenni009** [comment]
It says "Review required" :/

**Comment by Khaoz-Topsy** [comment]
Sorry I am too used Azure DevOps these days 😂. There should be a comment and approve button! 😅

**Comment by Lenni009** [comment]
There is a comment and approve button, when you click on "Files changed", then "Review changes" on the top right. But I can bypass the review mechanism, so I just did that instead now. Only works when automerge is disabled though. And I hate bypassing branch protection

**Comment by Khaoz-Topsy** [comment]
True true, I just have to get better 😝

**Pull request merged**
