### PR TITLE
add image compressor

### PR DESCRIPTION
**Pull request by Lenni009**
The `develop` branch seems to be behind `main`, so I opened the PR to `main`. Let me know if I should change that.

### CODE REVIEW

**Comment by Khaoz-Topsy** [comment]
Sweet! Will you increment the version in the package.json as well? Then PR is all good 😁

**Review by Khaoz-Topsy — APPROVED** [review]

**Comment by Lenni009** [comment]
package.json version is 2.1.5, the same as package-lock.json. Should I increment both to 2.1.6?

**Comment by Khaoz-Topsy** [comment]
Yes please 😋

**Comment by Lenni009** [comment]
Done

**Review by Khaoz-Topsy — APPROVED** [review]

**Pull request merged**
